name: tfemby-web

services:
  tfemby-web:
    image: xiaotong378/tfembyweb:latest
    container_name: tfemby-web
    ports:
      - "8787:8787"
    environment:
      - PORT=8787
      - DATA_DIR=/data
      - TGBOT_URL=http://tgbot:8099
    volumes:
      - tfemby-web-data:/data
    restart: unless-stopped
    depends_on:
      - tgbot

  tgbot:
    image: xiaotong378/tgbot:1.1.5
    container_name: tfemby-tgbot
    ports:
      - "8099:8099"
    volumes:
      - tfemby-tgbot-data:/app/data
    restart: unless-stopped

volumes:
  tfemby-web-data:
  tfemby-tgbot-data:
